---
title: "Project self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing

### Editing

Edited the abstract a bit. Initially it said that only oxygen concentrations were significant, but they werent, it was NH4 concentrations only for the OTU based data.

## Introduction

### Literature research

I found and cited most of the references that we used in the introduction (sources 1-12). I also found one of the sources used in the discussion (18) 

### Writing

I wrote the first draft of the introduction. Note: Ian wrote and edited a good portion of the section on planctomycetes for the second draft.

### Editing

I edited the introduction as well, and combined my and Ian's sections on planctomycetes.  

## Methods
### Writing

### Editing

I made some gramatical edits to the methods section after it was written. I also compiled the total reference list: since we each worked on the sections separately, there were reference sections for each of the individual sections.  

## Results
### Anaysis 

I wrote the section of the analysis that analyzed the figures that I made: 3g and 3h. This section was on the importance of abundance related to NH4 concentration and its predicted impact on annamox activity.

### Figures

I made the figure 3c: "Abundance of OTUs within Planctomycetes across depth" (OTUs)
and "Abundance of Planctomycetes across depth" (OTUs) by adapting code provided in class by Dr. Dill-McFarland to describe planctomycetes. The "Abundance of OTUs within Planctomycetes across depth" did not end up being included in the report, because there are a lot of different OTUs for planctomycetes, and there was just too many smaller plots to really convey any information (there are 110 different OTUs within planctomycetes). On the plus side, this meant that we did not have to adjust the code and re make this figure for ASVs. 

I also made figures 3g and 3h "Abundance of Planctomycetes across NH4 concentration (OTUs)" and "Abundance of Planctomycetes across NH4 concentration (ASVs)". 

Lastly, I adjusted the code for and performed the analysis of the p values of the linear relationship of abundance of planctomycetes across NH4 concentration for OTUs and ASVs. This is the data presented in the last column of Table 1: p-values for Planctomycetes abundance with respect to depth and oxygen and ammonium concentration

### Writing

I wrote the first draft of the section on the Abundance of Planctomycetes across NH4 concetration (the third paragraph of the analysis of figures 3a-h and table 1).


### Editing

Made some gramatical changes in the analysis of figures 3a-f and table 1.

## Discussion

### Literature research

Found and cited source 18. 

### Writing

I began writing the first draft of the discussion section (the part on planctomycetes abundance across depth). 
After the other members of my group did some more work on the discussion section, I rewrote and lengthened the part on the relationship of planctomycetes and oxygen (paragraph 2) to help bring it up to 750 words (from 494 words)

### Editing

I also edited the discussion to make it more concise, and free of grammatical errors. 
